# -*- coding: utf-8 -*-
"""GoldPricePrediction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hh9O9027RoSrqqT8zotQAj8jxUiLPzQj
"""

import zipfile
import os
with zipfile.ZipFile('GoldPrices.zip','r') as zip_ref:
  zip_ref.extractall('gold_extracted')
  print("All File Extracted!")
  print(os.listdir('gold_extracted'))

import pandas as pd
df = pd.read_csv('gold_extracted/Daily.csv')

print("---Column Names---")
print(df.columns.tolist())
print("\n---Data Samples---")
print(df.head())

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler


columns_to_use = ['USD']

df['Date'] = pd.to_datetime(df.iloc[:, 0])
df.set_index('Date', inplace=True)


for col in columns_to_use:
    if df[col].dtype == 'O':
        df[col] = df[col].str.replace(',', '').astype(float)
    else:
        df[col] = df[col].astype(float)

df_cleaned = df[columns_to_use].fillna(method='ffill').dropna()

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df_cleaned)

print("Data Cleaning Finished!")
print(f"Shape after cleaning: {scaled_data.shape}")

X, y = [], []
time_step = 60

for i in range(time_step, len(scaled_data)):
    X.append(scaled_data[i-time_step:i, 0])
    y.append(scaled_data[i, 0])

X, y = np.array(X), np.array(y)


X = X.reshape(X.shape[0], X.shape[1], 1)

print("X shape:", X.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(X.shape[1], 1)),
    Dropout(0.2),
    LSTM(50, return_sequences=False),
    Dropout(0.2),
    Dense(25),
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X, y, batch_size=32, epochs=10)